spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.sambasoft.model

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  docker:
    compose:
      lifecycle-management: start_and_stop
  jpa:
    hibernate:
      ddl-auto: create-drop

topic:
  name: order-topic
